name: F1-Jokers Build Pipeline

on:
  push:
    branches: [ "Develop" ] 
  pull_request:
    branches: [ "Develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      run: dotnet test F1Jokers.Tests/F1Jokers.Tests.csproj --verbosity normal
